package ir.ac.kntu.helpers;

public enum MenuLevel {
    WITHOUT_USER,
    MAIN_MENU,
    COURSES,
    SEARCH,
    USER,
    OWNED_COURSE_MENU,
    NORMAL_COURSE_MENU,
    UNPARTICIPATED_COURSE_MENU,
    HOMEWORKS,
    OWNED_HOMEWORK_MENU,
    NORMAL_HOMEWORK_MENU,
    Questions,
    OWNED_QUESTION_MENU,
    NORMAL_QUESTION_MENU,
    ANSWERS,
    NORMAL_ANSWER_MENU,
    OTHER_ANSWER_MENU,
    QUESTION_BANK,
    QUESTION_IN_BANK,
    EXIT;
}